$LOAD_PATH.unshift File.expand_path(File.join('..', 'lib'), File.dirname(__FILE__))
require 'distributed/test_communication'
require 'distributed/test_connection'
require 'distributed/test_execution'
require 'distributed/test_mixed_plan'
require 'distributed/test_plan_notifications'
require 'distributed/test_protocol'
require 'distributed/test_query'
require 'distributed/test_remote_plan'
require 'distributed/test_transaction'
