require 'roby/test/self'
require './test/actions/models/test_interface'
require './test/actions/models/test_action'
require './test/actions/models/test_method_action'
require './test/actions/models/test_coordination_action'
require './test/actions/test_task'
require './test/actions/test_action'
require './test/actions/test_library'
