require 'roby/test/self'
require './test/relations/test_space'
require './test/relations/test_graph'
require './test/relations/test_fork_merge_visitor'
require './test/relations/test_bidirectional_directed_adjacency_graph'
require './test/task_structure/test_dependency'
require './test/task_structure/test_executed_by'
require './test/task_structure/test_planned_by'
require './test/task_structure/test_conflicts'
require './test/task_structure/test_error_handling'
require './test/event_structure/test_temporal_constraints'

