require 'roby/test/self'
require './test/interface/test_client'
require './test/interface/test_interface'
require './test/interface/test_command_library'
require './test/interface/async/test_interface'
