if ENV['ROBY_ROOT_DIR']
    $LOAD_PATH << File.join(ENV['ROBY_ROOT_DIR'], 'lib')
end
require 'roby/app/plugins/rake'

Roby::Rake.plugin_doc("fault_injection") do |rdoc|
  rdoc.title    = "Fault injection plugin for Roby"
  rdoc.options << '--main' << 'README.txt'
  rdoc.rdoc_files.include('README.txt', 'TODO.txt', 'History.txt')
  rdoc.rdoc_files.include('fault_injection.rb', 'app.rb')
end

