if ENV['ROBY_ROOT_DIR']
    $LOAD_PATH << File.join(ENV['ROBY_ROOT_DIR'], 'lib')
end
require 'roby/app/plugins/rake'

Roby::Rake.plugin_doc("subsystems") do |rdoc|
  rdoc.title    = "Subsystems plugin for Roby"
  rdoc.template = Roby::Rake.rdoc_template
  rdoc.options << '--main' << 'README.txt'
  rdoc.rdoc_files.include('README.txt')
  rdoc.rdoc_files.include('app.rb')
end

