#! /usr/bin/env ruby
# frozen_string_literal: true

io = File.open(ARGV.first, "w")

trap("INT") do
    io.puts "INT"
    io.close
    exit 1
end

trap("USR1") do
    io.puts "USR1"
    io.close
    exit 1
end

io.puts "READY"
io.flush
STDIN.readline
